services:
  postgres:
    image: postgres:14-alpine
    ports:
      - 5432:5432
    volumes:
      - postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=Passw0rd
      - POSTGRES_USER=timemanager_user
      - POSTGRES_DB=timemanager_db
      
  elixir:
    build: ./timemanager
    environment:
      - MIX_ENV=prod
      - SECRET_KEY_BASE=secret_key_base
      - DATABASE_URL=ecto://timemanager_user:Passw0rd@postgres/timemanager_db
      - JWT_PASSPHRASE=Passw0rd
    ports:
      - "4000:4000"
    depends_on:
      - postgres

  pgadmin:
    image: dpage/pgadmin4
    ports:
      - "4002:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: user@domain.com
      PGADMIN_DEFAULT_PASSWORD: secret
    volumes:
      - pgadmin-data:/var/lib/pgadmin

  swagger-ui:
    image: swaggerapi/swagger-ui
    ports:
      - "4001:8080"
    volumes:
      - ./timemanager/swagger.json:/openapi.json
    environment:
      SWAGGER_JSON: /openapi.json

  vuejs:
    build: ./app
    ports:
      - "80:80"

volumes:
  postgres: {}
  pgadmin-data: {}